wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1645069635
    t:
      1:
      - 5
      2:
      - 5
      4: 3.8.12
      5: 0.12.9
      8:
      - 5
export_artifact:
  desc: null
  value: model_export
numerical_pipe:
  desc: null
  value:
    model: 0
svm:
  desc: null
  value:
    C: 5.0
    cache_size: 2048
    coef0: 4
    degree: 3
    gamma: auto
    kernel: sigmoid
    max_iter: -1
    probability: false
    shrinking: true
    tol: 0.01
    verbose: false
